//! Full-decode parity test for the diffusion video VAE decoder.
//!
//! Fixture: `tests/fixtures/parity.safetensors` — generated by
//! `tools/parity/ltx-vae-decoder.py` using the reference venv.
//!
//! Tolerances: atol=1e-4, rtol=1e-3 (float32 on CPU).

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::approx_constant,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::as_conversions,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::similar_names,
    clippy::cast_precision_loss
)]

use std::path::PathBuf;

use burn::backend::{NdArray, ndarray::NdArrayDevice};
use burn::tensor::Tensor;
use ltx_vae_decoder::{DecoderConfig, DiffusionVideoDecoder};
use ltx_weights::{KeyMap, WeightStore};

type B = NdArray;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

#[test]
fn parity_full_decode() {
    let fixture_path = fixture("parity.safetensors");
    assert!(
        fixture_path.exists(),
        "parity fixture not found at {}: run tools/parity/ltx-vae-decoder.py first",
        fixture_path.display()
    );

    let store = WeightStore::open(&[&fixture_path], &KeyMap::identity()).unwrap();

    // ── Load config from fixture metadata ─────────────────────────────────
    let config_str = store
        .metadata("config")
        .expect("fixture must have 'config' metadata");
    let config_json: serde_json::Value =
        serde_json::from_str(config_str).expect("config metadata must be valid JSON");
    let config =
        DecoderConfig::from_vae_json(&config_json).expect("config must deserialize cleanly");

    // ── Build decoder from scope (same key names as Python state_dict) ─────
    let device = NdArrayDevice::default();
    let scope = store.scope("");
    let decoder = DiffusionVideoDecoder::<B>::load(&scope, &config, &device)
        .expect("decoder must load without error");

    // ── Load inputs ────────────────────────────────────────────────────────
    let latent_host = store
        .read("input_latent")
        .expect("fixture must have input_latent");
    let noise_host = store
        .read("input_noise")
        .expect("fixture must have input_noise");
    let expected_host = store
        .read("output_pixels")
        .expect("fixture must have output_pixels");

    let latent: Tensor<B, 5> = latent_host
        .into_tensor(&device)
        .expect("input_latent must be 5-D");
    let noise: Tensor<B, 5> = noise_host
        .into_tensor(&device)
        .expect("input_noise must be 5-D");
    let expected: Tensor<B, 5> = expected_host
        .into_tensor(&device)
        .expect("output_pixels must be 5-D");

    // ── Run full decode ────────────────────────────────────────────────────
    let pixels = decoder
        .decode(latent, Some(noise), &device)
        .expect("decode must succeed");

    // ── Compare outputs ────────────────────────────────────────────────────
    let atol = 1e-4_f32;
    let rtol = 1e-3_f32;

    let pixels_data = pixels.into_data().convert::<f32>();
    let expected_data = expected.into_data().convert::<f32>();

    assert_eq!(
        pixels_data.shape, expected_data.shape,
        "output shape mismatch: Rust={:?}  Python={:?}",
        pixels_data.shape, expected_data.shape,
    );

    let got_vals = pixels_data
        .as_slice::<f32>()
        .expect("pixels must be f32 slice");
    let exp_vals = expected_data
        .as_slice::<f32>()
        .expect("expected must be f32 slice");

    let mut max_abs_err = 0.0_f32;
    let mut fail_count = 0_usize;
    let total = got_vals.len();

    for (idx, (got, exp)) in got_vals.iter().zip(exp_vals.iter()).enumerate() {
        let abs_diff = (got - exp).abs();
        let tol = rtol.mul_add(exp.abs(), atol);
        if abs_diff > tol {
            fail_count += 1;
            if fail_count <= 5 {
                eprintln!(
                    "  element {idx}: got={got:.6}  exp={exp:.6}  diff={abs_diff:.2e}  tol={tol:.2e}"
                );
            }
        }
        if abs_diff > max_abs_err {
            max_abs_err = abs_diff;
        }
    }

    println!("parity_full_decode: max_abs_err={max_abs_err:.2e}  failures={fail_count}/{total}");

    assert_eq!(
        fail_count, 0,
        "parity_full_decode: {fail_count}/{total} elements exceeded tolerance \
         (atol={atol}, rtol={rtol}); max abs err = {max_abs_err:.2e}"
    );
}

// ─── Helper ──────────────────────────────────────────────────────────────────

/// Load decoder + inputs from a scale fixture and return `(decoder, latent, noise, expected)`.
fn load_scale_fixture(
    fixture_name: &str,
    expected_key: &str,
) -> (
    DiffusionVideoDecoder<B>,
    Tensor<B, 5>,
    Tensor<B, 5>,
    Tensor<B, 5>,
) {
    let fixture_path = fixture(fixture_name);
    assert!(
        fixture_path.exists(),
        "scale parity fixture not found at {}: \
         run tools/parity/ltx-vae-decoder-scale.py first",
        fixture_path.display()
    );

    let device = NdArrayDevice::default();
    let store = WeightStore::open(&[&fixture_path], &KeyMap::identity()).unwrap();

    let config_str = store.metadata("config").expect("fixture must have config");
    let config_json: serde_json::Value =
        serde_json::from_str(config_str).expect("config must be valid JSON");
    let config = DecoderConfig::from_vae_json(&config_json).expect("config must deserialize");

    let scope = store.scope("");
    let decoder =
        DiffusionVideoDecoder::<B>::load(&scope, &config, &device).expect("decoder must load");

    let latent: Tensor<B, 5> = store
        .read("input_latent")
        .expect("fixture must have input_latent")
        .into_tensor(&device)
        .expect("input_latent must be 5-D");
    let noise: Tensor<B, 5> = store
        .read("input_noise")
        .expect("fixture must have input_noise")
        .into_tensor(&device)
        .expect("input_noise must be 5-D");
    let expected: Tensor<B, 5> = store
        .read(expected_key)
        .expect("fixture must have expected output")
        .into_tensor(&device)
        .expect("expected must be 5-D");

    (decoder, latent, noise, expected)
}

/// Check element-wise tolerance; return `(max_abs_err, fail_count)`.
fn check_tolerance(
    got: &Tensor<B, 5>,
    exp: &Tensor<B, 5>,
    atol: f32,
    rtol: f32,
    tag: &str,
) -> (f32, usize) {
    let got_data = got.clone().into_data().convert::<f32>();
    let exp_data = exp.clone().into_data().convert::<f32>();

    assert_eq!(
        got_data.shape, exp_data.shape,
        "{tag}: shape mismatch: Rust={:?}  Python={:?}",
        got_data.shape, exp_data.shape,
    );

    let got_vals = got_data.as_slice::<f32>().expect("must be f32");
    let exp_vals = exp_data.as_slice::<f32>().expect("must be f32");

    let mut max_abs_err = 0.0_f32;
    let mut fail_count = 0_usize;
    let total = got_vals.len();

    for (idx, (g, e)) in got_vals.iter().zip(exp_vals.iter()).enumerate() {
        let diff = (g - e).abs();
        let tol = rtol.mul_add(e.abs(), atol);
        if diff > tol {
            fail_count += 1;
            if fail_count <= 5 {
                eprintln!(
                    "  [{tag}] element {idx}: got={g:.6}  exp={e:.6}  diff={diff:.2e}  tol={tol:.2e}"
                );
            }
        }
        if diff > max_abs_err {
            max_abs_err = diff;
        }
    }
    println!("{tag}: max_abs_err={max_abs_err:.2e}  failures={fail_count}/{total}");
    (max_abs_err, fail_count)
}

// ─── Test: edge + interior windows ───────────────────────────────────────────

/// Parity on a canvas where every NA axis has both clamped-edge and
/// unclamped-interior window positions.
///
/// Fixture: `parity_scale_edge_interior.safetensors`
/// Generated by: `tools/parity/ltx-vae-decoder-scale.py`
///
/// Tolerances: atol=1e-4, rtol=1e-3 (same as the base parity test).
#[test]
fn parity_edge_interior_windows() {
    let (decoder, latent, noise, expected) =
        load_scale_fixture("parity_scale_edge_interior.safetensors", "output_pixels");

    let device = NdArrayDevice::default();
    let pixels = decoder
        .decode(latent, Some(noise), &device)
        .expect("decode must succeed");

    let atol = 1e-4_f32;
    let rtol = 1e-3_f32;
    let (_, fail_count) = check_tolerance(&pixels, &expected, atol, rtol, "edge_interior");

    assert_eq!(
        fail_count, 0,
        "parity_edge_interior_windows: {fail_count} elements exceeded \
         tolerance (atol={atol}, rtol={rtol})"
    );
}

// ─── Test: 2×2 spatial tiling ────────────────────────────────────────────────

/// Parity for `decode_with_tiling` against a reference 2×2 spatial tile
/// schedule (no temporal tiling, non-overlapping tiles → masks = 1.0).
///
/// Fixture: `parity_scale_tiled.safetensors`
/// Generated by: `tools/parity/ltx-vae-decoder-scale.py`
///
/// Tolerances: atol=5e-3, rtol=5e-2 (slightly looser because each tile
/// decodes independently, accumulating different floating-point paths).
#[test]
fn parity_tiled_decode() {
    use ltx_vae_decoder::{DecodeTileConfig, TileDim};

    let fixture_path = fixture("parity_scale_tiled.safetensors");
    assert!(
        fixture_path.exists(),
        "tiled parity fixture not found: run tools/parity/ltx-vae-decoder-scale.py first"
    );

    let device = NdArrayDevice::default();
    let store = WeightStore::open(&[&fixture_path], &KeyMap::identity()).unwrap();

    let config_str = store.metadata("config").expect("fixture must have config");
    let config_json: serde_json::Value =
        serde_json::from_str(config_str).expect("config must be valid JSON");
    let config = DecoderConfig::from_vae_json(&config_json).expect("config must deserialize");

    let scope = store.scope("");
    let decoder =
        DiffusionVideoDecoder::<B>::load(&scope, &config, &device).expect("decoder must load");

    let latent: Tensor<B, 5> = store
        .read("input_latent")
        .expect("must have input_latent")
        .into_tensor(&device)
        .expect("must be 5-D");
    let noise: Tensor<B, 5> = store
        .read("input_noise")
        .expect("must have input_noise")
        .into_tensor(&device)
        .expect("must be 5-D");
    let expected: Tensor<B, 5> = store
        .read("output_pixels_tiled")
        .expect("must have output_pixels_tiled")
        .into_tensor(&device)
        .expect("must be 5-D");

    // Load the tile half-size stored by the Python script.
    let half_h_data = store
        .read("tile_half_ctx_h")
        .expect("must have tile_half_ctx_h")
        .into_tensor::<B, 1>(&device)
        .expect("must be 1-D");
    let half_w_data = store
        .read("tile_half_ctx_w")
        .expect("must have tile_half_ctx_w")
        .into_tensor::<B, 1>(&device)
        .expect("must be 1-D");

    let half_h = half_h_data
        .into_data()
        .convert::<f32>()
        .as_slice::<f32>()
        .expect("half_h must be f32")[0] as usize;
    let half_w = half_w_data
        .into_data()
        .convert::<f32>()
        .as_slice::<f32>()
        .expect("half_w must be f32")[0] as usize;

    // Build the same 2×2 spatial tile config.
    // half_h and half_w are in canvas-pixel units.
    let tile_cfg = DecodeTileConfig {
        frames: TileDim {
            tile_size: 0,
            overlap: 0,
        }, // no temporal tiling
        height: TileDim {
            tile_size: half_h,
            overlap: 0,
        },
        width: TileDim {
            tile_size: half_w,
            overlap: 0,
        },
    };

    let pixels = decoder
        .decode_with_tiling(latent, Some(noise), Some(&tile_cfg), &device)
        .expect("tiled decode must succeed");

    let atol = 5e-3_f32;
    let rtol = 5e-2_f32;
    let (_, fail_count) = check_tolerance(&pixels, &expected, atol, rtol, "tiled_decode");

    assert_eq!(
        fail_count, 0,
        "parity_tiled_decode: {fail_count} elements exceeded \
         tolerance (atol={atol}, rtol={rtol})"
    );
}
