//! Full-decode parity test for the diffusion video VAE decoder.
//!
//! Fixture: `tests/fixtures/parity.safetensors` — generated by
//! `tools/parity/ltx-vae-decoder.py` using the reference venv.
//!
//! Tolerances: atol=1e-4, rtol=1e-3 (float32 on CPU).

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::approx_constant,
    clippy::indexing_slicing
)]

use std::path::PathBuf;

use burn::backend::NdArray;
use burn::tensor::Tensor;
use ltx_vae_decoder::{DecoderConfig, DiffusionVideoDecoder};
use ltx_weights::{KeyMap, WeightStore};

type B = NdArray;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

#[test]
fn parity_full_decode() {
    let fixture_path = fixture("parity.safetensors");
    assert!(
        fixture_path.exists(),
        "parity fixture not found at {}: run tools/parity/ltx-vae-decoder.py first",
        fixture_path.display()
    );

    let store = WeightStore::open(&[&fixture_path], &KeyMap::identity()).unwrap();

    // ── Load config from fixture metadata ─────────────────────────────────
    let config_str = store
        .metadata("config")
        .expect("fixture must have 'config' metadata");
    let config_json: serde_json::Value =
        serde_json::from_str(config_str).expect("config metadata must be valid JSON");
    let config =
        DecoderConfig::from_vae_json(&config_json).expect("config must deserialize cleanly");

    // ── Build decoder from scope (same key names as Python state_dict) ─────
    let device = Default::default();
    let scope = store.scope("");
    let decoder = DiffusionVideoDecoder::<B>::load(&scope, &config, &device)
        .expect("decoder must load without error");

    // ── Load inputs ────────────────────────────────────────────────────────
    let latent_host = store
        .read("input_latent")
        .expect("fixture must have input_latent");
    let noise_host = store
        .read("input_noise")
        .expect("fixture must have input_noise");
    let expected_host = store
        .read("output_pixels")
        .expect("fixture must have output_pixels");

    let latent: Tensor<B, 5> = latent_host
        .into_tensor(&device)
        .expect("input_latent must be 5-D");
    let noise: Tensor<B, 5> = noise_host
        .into_tensor(&device)
        .expect("input_noise must be 5-D");
    let expected: Tensor<B, 5> = expected_host
        .into_tensor(&device)
        .expect("output_pixels must be 5-D");

    // ── Run full decode ────────────────────────────────────────────────────
    let pixels = decoder
        .decode(latent, Some(noise), &device)
        .expect("decode must succeed");

    // ── Compare outputs ────────────────────────────────────────────────────
    let atol = 1e-4_f32;
    let rtol = 1e-3_f32;

    let pixels_data = pixels.into_data().convert::<f32>();
    let expected_data = expected.into_data().convert::<f32>();

    assert_eq!(
        pixels_data.shape, expected_data.shape,
        "output shape mismatch: Rust={:?}  Python={:?}",
        pixels_data.shape, expected_data.shape,
    );

    let got_vals = pixels_data
        .as_slice::<f32>()
        .expect("pixels must be f32 slice");
    let exp_vals = expected_data
        .as_slice::<f32>()
        .expect("expected must be f32 slice");

    let mut max_abs_err = 0.0_f32;
    let mut fail_count = 0_usize;
    let total = got_vals.len();

    for (idx, (got, exp)) in got_vals.iter().zip(exp_vals.iter()).enumerate() {
        let abs_diff = (got - exp).abs();
        let tol = atol + rtol * exp.abs();
        if abs_diff > tol {
            fail_count += 1;
            if fail_count <= 5 {
                eprintln!(
                    "  element {idx}: got={got:.6}  exp={exp:.6}  diff={abs_diff:.2e}  tol={tol:.2e}"
                );
            }
        }
        if abs_diff > max_abs_err {
            max_abs_err = abs_diff;
        }
    }

    println!("parity_full_decode: max_abs_err={max_abs_err:.2e}  failures={fail_count}/{total}");

    assert_eq!(
        fail_count, 0,
        "parity_full_decode: {fail_count}/{total} elements exceeded tolerance \
         (atol={atol}, rtol={rtol}); max abs err = {max_abs_err:.2e}"
    );
}
