//! Parity test: compare [`VideoTransformer::forward`] against the Python
//! fixture generated by `tools/parity/ltx-dit.py` (LTX-2 commit 9ec55f9).
//!
//! The fixture is `tests/fixtures/dit_parity.safetensors` and holds the
//! reference model's `state_dict()` weights plus a set of random-init inputs
//! and the reference output produced with `torch.manual_seed(42)`.
//!
//! Tolerances: absolute `1e-4`, relative `1e-3` (f32 on CPU ndarray vs
//! `PyTorch` CPU math SDPA at float32 precision).

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::approx_constant,
    clippy::doc_markdown
)]

use std::path::PathBuf;

use burn::backend::NdArray;
use burn::backend::ndarray::NdArrayDevice;
use burn::prelude::*;
use ltx_dit::{DiTConfig, OffloadMode, VideoInput, VideoTransformer};
use ltx_weights::{KeyMap, WeightStore};

type B = NdArray;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

/// Absolute tolerance: tight f32 agreement between `PyTorch` CPU math SDPA
/// and Burn ndarray.
const ATOL: f32 = 1e-4;
/// Relative tolerance.
const RTOL: f32 = 1e-3;

fn assert_tensors_close(got: &[f32], expected: &[f32], name: &str) {
    assert_eq!(got.len(), expected.len(), "{name}: length mismatch");
    let mut max_abs = 0.0_f32;
    let mut max_rel = 0.0_f32;
    for (i, (&g, &e)) in got.iter().zip(expected).enumerate() {
        let abs = (g - e).abs();
        let rel = abs / (e.abs() + 1e-8_f32);
        if abs > max_abs {
            max_abs = abs;
        }
        if rel > max_rel {
            max_rel = rel;
        }
        assert!(
            abs <= ATOL || rel <= RTOL,
            "{name}[{i}]: got={g} expected={e} abs={abs:.2e} rel={rel:.2e} \
             (atol={ATOL:.1e} rtol={RTOL:.1e})"
        );
    }
    println!("{name}: max_abs={max_abs:.2e} max_rel={max_rel:.2e}");
}

#[test]
fn parity_video_transformer() {
    let path = fixture("dit_parity.safetensors");
    assert!(
        path.exists(),
        "fixture not found: {}\nRun: python -W ignore tools/parity/ltx-dit.py",
        path.display()
    );

    let store = WeightStore::open(&[&path], &KeyMap::identity()).unwrap();
    let device = NdArrayDevice::default();

    // ── Load config from fixture metadata ────────────────────────────────────
    // The fixture stores config at the root level (no nested "transformer" key).
    let cfg_json = store.config().unwrap();
    let cfg_val = cfg_json.get("transformer").unwrap_or(&cfg_json);
    let config = DiTConfig::from_json(cfg_val).unwrap();

    // ── Load model weights ────────────────────────────────────────────────────
    let scope = store.scope("");
    let model: VideoTransformer<B> = VideoTransformer::load(&scope, &config, &device).unwrap();

    // ── Load inputs ───────────────────────────────────────────────────────────
    let latent: Tensor<B, 3> = scope.tensor("input.latent", &device).unwrap();
    let timesteps: Tensor<B, 2> = scope.tensor("input.timesteps", &device).unwrap();
    let positions: Tensor<B, 4> = scope.tensor("input.positions", &device).unwrap();
    let context: Tensor<B, 3> = scope.tensor("input.context", &device).unwrap();
    let expected_host = store.read("output").unwrap();

    // ── Run forward ───────────────────────────────────────────────────────────
    let input = VideoInput {
        latent,
        timesteps,
        positions,
        context,
        context_mask: None, // alpha_gen passes no context mask
        self_attn_mask: None,
    };

    let output = model.forward(input, OffloadMode::Resident, &device);

    // ── Compare ───────────────────────────────────────────────────────────────
    let got: Vec<f32> = output.into_data().to_vec().unwrap();
    assert_tensors_close(&got, &expected_host.data, "output");
}
