//! Parity tests: compare [`VideoTransformer::forward`] against Python fixtures
//! generated by `tools/parity/ltx-dit.py` (LTX-2 commit 9ec55f9).
//!
//! Two fixtures:
//! - `dit_parity.safetensors` — 22B-default flags (all off), seed 42.
//! - `dit_parity_gated_adaln.safetensors` — non-default flags on
//!   (`apply_gated_attention=True`, `cross_attention_adaln=True`,
//!   `use_prompt_adaln_single=False`, `ff_bias=True`), seed 99.
//!
//! Tolerances: absolute `1e-4`, relative `1e-3` (f32 on CPU ndarray vs
//! `PyTorch` CPU math SDPA at float32 precision).

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::approx_constant
)]

use std::path::PathBuf;

use burn::backend::NdArray;
use burn::backend::ndarray::NdArrayDevice;
use burn::prelude::*;
use ltx_dit::{DiTConfig, OffloadMode, VideoInput, VideoTransformer};
use ltx_weights::{KeyMap, WeightStore};

type B = NdArray;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

/// Absolute tolerance: tight f32 agreement between `PyTorch` CPU math SDPA
/// and Burn ndarray.
const ATOL: f32 = 1e-4;
/// Relative tolerance.
const RTOL: f32 = 1e-3;

fn assert_tensors_close(got: &[f32], expected: &[f32], name: &str) {
    assert_eq!(got.len(), expected.len(), "{name}: length mismatch");
    let mut max_abs = 0.0_f32;
    let mut max_rel = 0.0_f32;
    for (i, (&g, &e)) in got.iter().zip(expected).enumerate() {
        let abs = (g - e).abs();
        let rel = abs / (e.abs() + 1e-8_f32);
        if abs > max_abs {
            max_abs = abs;
        }
        if rel > max_rel {
            max_rel = rel;
        }
        assert!(
            abs <= ATOL || rel <= RTOL,
            "{name}[{i}]: got={g} expected={e} abs={abs:.2e} rel={rel:.2e} \
             (atol={ATOL:.1e} rtol={RTOL:.1e})"
        );
    }
    println!("{name}: max_abs={max_abs:.2e} max_rel={max_rel:.2e}");
}

#[test]
fn parity_video_transformer() {
    let path = fixture("dit_parity.safetensors");
    assert!(
        path.exists(),
        "fixture not found: {}\nRun: python -W ignore tools/parity/ltx-dit.py",
        path.display()
    );

    let store = WeightStore::open(&[&path], &KeyMap::identity()).unwrap();
    let device = NdArrayDevice::default();

    // ── Load config from fixture metadata ────────────────────────────────────
    // The fixture stores config at the root level (no nested "transformer" key).
    let cfg_json = store.config().unwrap();
    let cfg_val = cfg_json.get("transformer").unwrap_or(&cfg_json);
    let config = DiTConfig::from_json(cfg_val).unwrap();

    // ── Load model weights ────────────────────────────────────────────────────
    let scope = store.scope("");
    let model: VideoTransformer<B> = VideoTransformer::load(&scope, &config, &device).unwrap();

    // ── Load inputs ───────────────────────────────────────────────────────────
    let latent: Tensor<B, 3> = scope.tensor("input.latent", &device).unwrap();
    let timesteps: Tensor<B, 2> = scope.tensor("input.timesteps", &device).unwrap();
    let positions: Tensor<B, 4> = scope.tensor("input.positions", &device).unwrap();
    let context: Tensor<B, 3> = scope.tensor("input.context", &device).unwrap();
    let expected_host = store.read("output").unwrap();

    // ── Run forward ───────────────────────────────────────────────────────────
    let input = VideoInput {
        latent,
        timesteps,
        positions,
        context,
        context_mask: None, // alpha_gen passes no context mask
        self_attn_mask: None,
    };

    let output = model.forward(input, OffloadMode::Resident, &device);

    // ── Compare ───────────────────────────────────────────────────────────────
    let got: Vec<f32> = output.into_data().to_vec().unwrap();
    assert_tensors_close(&got, &expected_host.data, "output");
}
/// Parity test: `apply_gated_attention=True`, `cross_attention_adaln=True`,
/// `use_prompt_adaln_single=False`, `ff_bias=True` (non-default flags, seed 99).
///
/// Exercises the gated-attention and cross-attention `AdaLN` forward paths that
/// the 22B checkpoint may enable via metadata keys.  All model parameters were
/// reset to `N(0, 0.02)` in the fixture to prevent NaN from `torch.empty`-
/// initialised `scale_shift_table` / `prompt_scale_shift_table` parameters.
#[test]
fn parity_video_transformer_gated_adaln() {
    let path = fixture("dit_parity_gated_adaln.safetensors");
    assert!(
        path.exists(),
        "fixture not found: {}\nRun: python -W ignore tools/parity/ltx-dit.py",
        path.display()
    );

    let store = WeightStore::open(&[&path], &KeyMap::identity()).unwrap();
    let device = NdArrayDevice::default();

    let cfg_json = store.config().unwrap();
    let cfg_val = cfg_json.get("transformer").unwrap_or(&cfg_json);
    let config = DiTConfig::from_json(cfg_val).unwrap();

    // Verify the flags we are testing are set.
    assert!(
        config.flags.apply_gated_attention,
        "fixture must have gated attention"
    );
    assert!(
        config.flags.cross_attention_adaln,
        "fixture must have cross-attention AdaLN"
    );
    assert!(config.flags.ff_bias, "fixture must have ff_bias=true");

    let scope = store.scope("");
    let model: VideoTransformer<B> = VideoTransformer::load(&scope, &config, &device).unwrap();

    let latent: Tensor<B, 3> = scope.tensor("input.latent", &device).unwrap();
    let timesteps: Tensor<B, 2> = scope.tensor("input.timesteps", &device).unwrap();
    let positions: Tensor<B, 4> = scope.tensor("input.positions", &device).unwrap();
    let context: Tensor<B, 3> = scope.tensor("input.context", &device).unwrap();
    let expected_host = store.read("output").unwrap();

    let input = VideoInput {
        latent,
        timesteps,
        positions,
        context,
        context_mask: None,
        self_attn_mask: None,
    };

    let output = model.forward(input, OffloadMode::Resident, &device);

    let got: Vec<f32> = output.into_data().to_vec().unwrap();
    assert_tensors_close(&got, &expected_host.data, "output (gated+adaln)");
}

// ── Error-path and branch-coverage tests ─────────────────────────────────────
//
// These tests use the parity fixture with a modified config to drive error
// and untested-flag code paths.  The fixture has a 2-block tiny model with
// apply_gated_attention=false and cross_attention_adaln=false (22B defaults).

/// Helper: load the fixture config.
fn fixture_config() -> DiTConfig {
    let path = fixture("dit_parity.safetensors");
    let store = WeightStore::open(&[&path], &KeyMap::identity()).unwrap();
    let cfg_json = store.config().unwrap();
    let cfg_val = cfg_json.get("transformer").unwrap_or(&cfg_json);
    DiTConfig::from_json(cfg_val).unwrap()
}

/// Helper: open the fixture store.
fn fixture_store() -> WeightStore {
    let path = fixture("dit_parity.safetensors");
    WeightStore::open(&[&path], &KeyMap::identity()).unwrap()
}

/// Load with `num_layers=3` but the fixture only has 2 blocks → missing key.
#[test]
fn load_missing_block_key_returns_error() {
    let path = fixture("dit_parity.safetensors");
    if !path.exists() {
        return; // skip if fixture absent
    }
    let store = fixture_store();
    let device = NdArrayDevice::default();
    let mut config = fixture_config();
    config.num_layers = 3; // block 2 keys are missing in the 2-block fixture

    let scope = store.scope("");
    let result = VideoTransformer::<B>::load(&scope, &config, &device);
    assert!(
        matches!(result, Err(ltx_dit::DitError::Weight(_))),
        "expected weight error for missing block key, got {result:?}"
    );
}

/// Load with wrong `attention_head_dim` → shape mismatch on `to_q.weight`.
#[test]
fn load_wrong_shape_returns_error() {
    let path = fixture("dit_parity.safetensors");
    if !path.exists() {
        return;
    }
    let store = fixture_store();
    let device = NdArrayDevice::default();
    let mut config = fixture_config();
    // The fixture has attention_head_dim=8; using 16 makes inner_dim=64,
    // so check_2d on to_q.weight fires (fixture has [32,32] not [64,64]).
    config.attention_head_dim = 16;

    let scope = store.scope("");
    let result = VideoTransformer::<B>::load(&scope, &config, &device);
    assert!(
        matches!(result, Err(ltx_dit::DitError::Weight(_))),
        "expected weight error for shape mismatch, got {result:?}"
    );
}

/// Load with `apply_gated_attention=true` → `to_gate_logits` keys are absent → error.
///
/// This exercises the gated-attention branch of `load_attention`, which is
/// NOT exercised by the main parity fixture (22B default: `apply_gated_attention=false`).
#[test]
fn load_gated_attn_missing_key_returns_error() {
    let path = fixture("dit_parity.safetensors");
    if !path.exists() {
        return;
    }
    let store = fixture_store();
    let device = NdArrayDevice::default();
    let mut config = fixture_config();
    config.flags.apply_gated_attention = true; // fixture has no to_gate_logits keys

    let scope = store.scope("");
    let result = VideoTransformer::<B>::load(&scope, &config, &device);
    assert!(
        matches!(result, Err(ltx_dit::DitError::Weight(_))),
        "expected weight error for missing to_gate_logits, got {result:?}"
    );
}

/// Load with `cross_attention_adaln=true` → `prompt_scale_shift_table` absent → error.
///
/// This exercises the `cross_attention_adaln` branch of `load_block`, which is
/// NOT exercised by the main parity fixture (22B default: `cross_attention_adaln=false`).
/// Note: [`DiTConfig::validate`] rejects `cross_attention_adaln=true` together with
/// `use_prompt_adaln_single=true` (not wired), so we disable the latter first.
#[test]
fn load_cross_attn_adaln_missing_key_returns_error() {
    let path = fixture("dit_parity.safetensors");
    if !path.exists() {
        return;
    }
    let store = fixture_store();
    let device = NdArrayDevice::default();
    let mut config = fixture_config();
    config.flags.cross_attention_adaln = true;
    config.flags.use_prompt_adaln_single = false; // required to pass validate()

    let scope = store.scope("");
    let result = VideoTransformer::<B>::load(&scope, &config, &device);
    assert!(
        matches!(result, Err(ltx_dit::DitError::Weight(_))),
        "expected weight error for missing prompt_scale_shift_table, got {result:?}"
    );
}
