//! End-to-end parity test for [`BurnBackend`].
//!
//! Fixture: `tests/fixtures/parity.safetensors` — generated by
//! `tools/parity/ltx-burn.py` using the reference venv.
//!
//! The fixture contains all model weights (encoder, decoder, transformer),
//! a tiny IC-LoRA, a prompt context, the exact noise tensors used by the
//! Python reference run, and the expected alpha output.
//!
//! The test builds `BurnBackend` from the component weights in the fixture
//! and calls `run_chunk_with_noise` to inject the recorded noise for a
//! deterministic comparison.
//!
//! Tolerance: `atol = 1e-3`, `rtol = 1e-2`

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::approx_constant,
    clippy::too_many_lines,
    clippy::arithmetic_side_effects
)]

use std::path::PathBuf;

use burn::backend::NdArray;
use burn::backend::ndarray::NdArrayDevice;
use burn::tensor::Tensor;
use ltx_backend::{Keyframes, VideoChunk};
use ltx_burn::{BurnBackend, GenerationSettings};
use ltx_dit::{DiTConfig, VideoTransformer};
use ltx_shape::IcLoraLayout;
use ltx_vae::{VaeEncoderConfig, VideoEncoder};
use ltx_vae_decoder::{DecoderConfig, DiffusionVideoDecoder};
use ltx_weights::{KeyMap, WeightStore};

type B = NdArray;

const ATOL: f32 = 1e-3;
const RTOL: f32 = 1e-2;

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/parity.safetensors")
}

fn assert_close(got: &[f32], expected: &[f32], name: &str) {
    assert_eq!(got.len(), expected.len(), "{name}: length mismatch");
    let mut max_abs = 0.0_f32;
    for (i, (&g, &e)) in got.iter().zip(expected.iter()).enumerate() {
        let abs = (g - e).abs();
        if abs > max_abs {
            max_abs = abs;
        }
        let tol = e.abs().mul_add(RTOL, ATOL);
        assert!(
            abs <= tol,
            "{name}[{i}]: got={g:.6}  exp={e:.6}  diff={abs:.2e}  tol={tol:.2e}"
        );
    }
    println!("{name}: max_abs_err = {max_abs:.2e}  (atol={ATOL:.0e} rtol={RTOL:.0e})");
}

/// Convert channels-first float data `[1, C, F, H, W]` from `[-1, 1]`
/// to interleaved `[F, H, W, C]` in `[0, 1]`.
fn chw_to_interleaved_01(data: &[f32], c: usize, f: usize, h: usize, w: usize) -> Vec<f32> {
    let mut out = vec![0.0_f32; f * h * w * c];
    for fi in 0..f {
        for hi in 0..h {
            for wi in 0..w {
                for ci in 0..c {
                    // Source index in [1, C, F, H, W] (batch dim dropped): c*F*H*W + f*H*W + h*W + w
                    let src = ci * f * h * w + fi * h * w + hi * w + wi;
                    // Destination index in [F, H, W, C]
                    let dst = fi * h * w * c + hi * w * c + wi * c + ci;
                    let val = data.get(src).copied().unwrap_or(0.0);
                    // [-1,1] → [0,1]
                    out[dst] = f32::midpoint(val, 1.0);
                }
            }
        }
    }
    out
}

/// Load models and build a [`BurnBackend`] from the parity fixture.
///
/// Returns `(backend, store, device)` so callers can access extra tensors
/// stored in the fixture (noise, expected alpha, etc.).
fn load_fixture_backend() -> (BurnBackend<B>, WeightStore, NdArrayDevice) {
    let path = fixture_path();
    assert!(
        path.exists(),
        "parity fixture not found at {}; run tools/parity/ltx-burn.py first",
        path.display()
    );

    let device = NdArrayDevice::default();
    let store = WeightStore::open(&[&path], &KeyMap::identity()).unwrap();

    let enc_cfg_str = store.metadata("encoder_config").expect("encoder_config");
    let enc_cfg_json: serde_json::Value = serde_json::from_str(enc_cfg_str).unwrap();
    let enc_cfg = VaeEncoderConfig::from_vae_json(&enc_cfg_json).unwrap();

    let dec_cfg_str = store.metadata("decoder_config").expect("decoder_config");
    let dec_cfg_json: serde_json::Value = serde_json::from_str(dec_cfg_str).unwrap();
    let dec_cfg = DecoderConfig::from_vae_json(&dec_cfg_json).unwrap();

    let tfm_cfg_str = store
        .metadata("transformer_config")
        .expect("transformer_config");
    let tfm_cfg_json: serde_json::Value = serde_json::from_str(tfm_cfg_str).unwrap();
    let dit_config =
        DiTConfig::from_json(tfm_cfg_json.get("transformer").unwrap_or(&tfm_cfg_json)).unwrap();

    let num_steps: u32 = store
        .metadata("num_inference_steps")
        .unwrap_or("2")
        .parse()
        .unwrap();
    let cfg_scale: f32 = store
        .metadata("cfg_scale")
        .unwrap_or("1.0")
        .parse()
        .unwrap();
    let frame_rate: f32 = store
        .metadata("frame_rate")
        .unwrap_or("24.0")
        .parse()
        .unwrap();
    let ds: u32 = store
        .metadata("lora_reference_downscale_factor")
        .unwrap_or("1")
        .parse()
        .unwrap();
    let ts: u32 = store
        .metadata("lora_reference_temporal_scale_factor")
        .unwrap_or("2")
        .parse()
        .unwrap();

    let encoder = VideoEncoder::<B>::load(&store.scope("enc"), &enc_cfg, &device).unwrap();
    let decoder = DiffusionVideoDecoder::<B>::load(&store.scope("dec"), &dec_cfg, &device).unwrap();
    let transformer =
        VideoTransformer::<B>::load(&store.scope("tfm"), &dit_config, &device).unwrap();

    let ctx_scope = store.scope("ctx");
    let positive_context: Tensor<B, 3> = ctx_scope
        .tensor("positive.video_encoding", &device)
        .unwrap();
    let negative_context: Option<Tensor<B, 3>> = ctx_scope
        .optional("negative.video_encoding", &device)
        .unwrap();

    let ic_layout = IcLoraLayout::new(ds, ts).unwrap();
    let settings = GenerationSettings {
        num_inference_steps: num_steps,
        cfg_scale,
        frame_rate,
    };
    let backend = BurnBackend::from_components(
        transformer,
        encoder,
        decoder,
        positive_context,
        negative_context,
        ic_layout,
        settings,
        device,
    );
    (backend, store, device)
}

#[test]
fn parity_end_to_end() {
    let (backend, store, device) = load_fixture_backend();

    let kf_strength: f32 = store
        .metadata("kf_strength")
        .unwrap_or("0.95")
        .parse()
        .unwrap();

    // ── Load test inputs ──────────────────────────────────────────────────────
    let rgb_raw: Vec<f32> = store
        .scope("")
        .tensor::<B, 5>("input_rgb", &device)
        .unwrap()
        .into_data()
        .convert::<f32>()
        .to_vec::<f32>()
        .unwrap();

    // rgb_raw is [1, 3, F, H, W] — parse dims from fixture metadata.
    let pf: u32 = store.metadata("pixel_f").unwrap_or("3").parse().unwrap();
    let ph: u32 = store.metadata("pixel_h").unwrap_or("4").parse().unwrap();
    let pw: u32 = store.metadata("pixel_w").unwrap_or("4").parse().unwrap();
    let f = usize::try_from(pf).unwrap();
    let h = usize::try_from(ph).unwrap();
    let w = usize::try_from(pw).unwrap();

    // Convert [1, 3, F, H, W] in [-1, 1] → interleaved [F, H, W, 3] in [0, 1].
    let frame_data = chw_to_interleaved_01(&rgb_raw, 3, f, h, w);
    let rgb_chunk = VideoChunk::new(0, pw, ph, pf, frame_data).expect("invalid VideoChunk");

    // Seam keyframe: [1, 3, 1, H, W] → interleaved [H, W, 3] in [0, 1].
    let kf_raw: Vec<f32> = store
        .scope("")
        .tensor::<B, 5>("input_kf_rgb", &device)
        .unwrap()
        .into_data()
        .convert::<f32>()
        .to_vec::<f32>()
        .unwrap();
    let kf_data = chw_to_interleaved_01(&kf_raw, 3, 1, h, w);
    let keyframes = Keyframes {
        frames: kf_data,
        indices: vec![0],
        strength: kf_strength,
        width: pw,
        height: ph,
        frame_count: 1,
    };

    // Noise tensors.
    let initial_noise: Tensor<B, 3> = store.scope("").tensor("initial_noise", &device).unwrap();
    let decoder_noise: Tensor<B, 5> = store.scope("").tensor("decoder_noise", &device).unwrap();

    // Expected alpha.
    let expected_alpha: Vec<f32> = store
        .scope("")
        .tensor::<B, 1>("output_alpha", &device)
        .unwrap()
        .into_data()
        .convert::<f32>()
        .to_vec::<f32>()
        .unwrap();

    // ── Run with injected noise and compare ───────────────────────────────────
    let alpha_chunk = backend
        .run_chunk_with_noise(
            &rgb_chunk,
            0,
            Some(&keyframes),
            initial_noise,
            decoder_noise,
        )
        .expect("run_chunk_with_noise failed");

    assert_eq!(
        alpha_chunk.data.len(),
        expected_alpha.len(),
        "alpha output length mismatch: got {} expected {}",
        alpha_chunk.data.len(),
        expected_alpha.len()
    );
    assert_close(&alpha_chunk.data, &expected_alpha, "output_alpha");
    println!(
        "parity_end_to_end passed: {} values, atol={ATOL:.0e}, rtol={RTOL:.0e}",
        alpha_chunk.data.len()
    );
}

#[test]
fn probe_returns_unsupported() {
    use ltx_backend::{AlphaBackend, BackendError};
    use ltx_shape::PixelShape;

    let (backend, _, _) = load_fixture_backend();
    let shape = PixelShape::new(9, 32, 32, ltx_shape::ScaleFactors::LTX2).unwrap();
    assert!(
        matches!(backend.probe(shape), Err(BackendError::Unsupported(_))),
        "probe() must return Err(Unsupported)"
    );
}
