//! Parity tests: compare Rust output against Python-generated fixtures.
//!
//! Fixtures are generated by `tools/parity/ltx-weights.py` using the
//! reference venv (LTX-2 commit 9ec55f9).  Each fixture is a safetensors
//! file in `tests/fixtures/`.
//!
//! Tolerances: absolute 1e-3 (fp32 on CPU; BF16 round-trip adds ≈ 0.001 ulp).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::approx_constant)]

use std::path::PathBuf;

use ltx_weights::{KeyMap, LoraFile, WeightStore};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

// ─── LoRA merge parity ────────────────────────────────────────────────────────

#[test]
fn parity_lora_merge_bf16() {
    let base_path = fixture("lora_parity_base.safetensors");
    let lora_path = fixture("lora_parity_lora.safetensors");
    let expected_path = fixture("lora_parity_expected.safetensors");

    let mut store = WeightStore::open(&[&base_path], &KeyMap::identity()).unwrap();
    let lora = LoraFile::open(&lora_path).unwrap();
    let report = store.merge_lora(&lora, 0.75).unwrap();
    assert!(report.matched_keys.contains(&"layer.weight".to_owned()));

    let rust_out = store.read("layer.weight").unwrap();

    let expected_store = WeightStore::open(&[&expected_path], &KeyMap::identity()).unwrap();
    let expected = expected_store.read("layer.weight").unwrap();

    assert_eq!(rust_out.shape, expected.shape, "shape mismatch");
    let abs_tol = 5e-2_f32; // BF16 ≈ 3 decimal digits
    for (i, (got, exp)) in rust_out.data.iter().zip(expected.data.iter()).enumerate() {
        assert!(
            (got - exp).abs() <= abs_tol,
            "element {i}: got {got}, expected {exp} (tol {abs_tol})"
        );
    }
}

// ─── FP8 dequantization parity ────────────────────────────────────────────────

#[test]
fn parity_fp8_e4m3fn_with_scale() {
    let fp8_path = fixture("fp8_e4m3fn_parity.safetensors");
    let expected_path = fixture("fp8_e4m3fn_expected.safetensors");

    let store = WeightStore::open(&[&fp8_path], &KeyMap::identity()).unwrap();
    let rust_out = store.read("w").unwrap();

    let expected_store = WeightStore::open(&[&expected_path], &KeyMap::identity()).unwrap();
    let expected = expected_store.read("w").unwrap();

    assert_eq!(rust_out.shape, expected.shape);
    let abs_tol = 1e-5_f32;
    for (i, (got, exp)) in rust_out.data.iter().zip(expected.data.iter()).enumerate() {
        // NaN values are equal (both sides dequant the same NaN sentinel).
        if exp.is_nan() {
            assert!(got.is_nan(), "element {i}: expected NaN, got {got}");
            continue;
        }
        assert!(
            (got - exp).abs() <= abs_tol,
            "element {i}: got {got}, expected {exp}"
        );
    }
}

// ─── Transformer KeyMap parity ────────────────────────────────────────────────

#[test]
fn parity_transformer_keymap() {
    let ckpt_path = fixture("transformer_keymap_fixture.safetensors");
    let expected_path = fixture("transformer_keymap_expected.safetensors");

    let store = WeightStore::open(&[&ckpt_path], &KeyMap::transformer()).unwrap();
    let expected = WeightStore::open(&[&expected_path], &KeyMap::identity()).unwrap();

    let key = "transformer_blocks.0.attn1.to_q.weight";
    assert!(store.contains(key), "key '{key}' not in transformer store");
    let got = store.read(key).unwrap();
    let exp = expected.read(key).unwrap();
    assert_eq!(got.shape, exp.shape);
    for (i, (g, e)) in got.data.iter().zip(exp.data.iter()).enumerate() {
        assert!((g - e).abs() < 1e-6_f32, "element {i}: {g} != {e}");
    }
}

// ─── IC-LoRA layout parity ────────────────────────────────────────────────────

#[test]
fn parity_iclora_layout() {
    let lora = LoraFile::open(fixture("iclora_layout.safetensors")).unwrap();
    let layout = lora.ic_layout().unwrap();
    assert_eq!(layout.reference_downscale(), 2);
    assert_eq!(layout.reference_temporal(), 4);
}
